/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

import (
	"net/http"
)

// APIKey provides API key based authentication to a request passed via context using ContextAPIKey
type APIKey struct {
	Key    string
	Prefix string
}

type Configuration struct {
	BasePath        string            `json:"basePath,omitempty"`
	Host            string            `json:"host,omitempty"`
	Scheme          string            `json:"scheme,omitempty"`
	DefaultHeader   map[string]string `json:"defaultHeader,omitempty"`
	UserAgent       string            `json:"userAgent,omitempty"`
	BearerTokenData *TokenData
	ApiKey          APIKey
	HTTPClient      *http.Client
}

func NewConfiguration(apiKey string) *Configuration {
	cfg := &Configuration{
		BasePath:      "https://api.perimeter81.biz/api/rest",
		DefaultHeader: make(map[string]string),
		UserAgent:     "Swagger-Codegen/1.0.0/go",
		ApiKey:        APIKey{Key: apiKey},
	}
	return cfg
}

func (c *Configuration) AddDefaultHeader(key string, value string) {
	c.DefaultHeader[key] = value
}
