/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type NetworkRegion struct {
	// ID of the network.
	Network string `json:"network"`
	// DNS of the region.
	Dns string `json:"dns"`
	// Name of the network region.
	Name string `json:"name"`
	// Network instances.
	Instances []NetworkInstance `json:"instances"`
	// Unique ID.
	Id string `json:"id"`
	// ID of the tenant.
	TenantId string `json:"tenantId"`
	// The date when this record was created.
	CreatedAt string `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt string `json:"updatedAt,omitempty"`
}
