/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

import (
	"time"
)

type OpenVpnTunnel struct {
	// Region ID
	RegionID string `json:"regionID"`
	// Gatwway ID
	GatewayID       string    `json:"gatewayID"`
	TunnelName      string    `json:"tunnelName"`
	TunnelID        string    `json:"tunnelID,omitempty"`
	Type_           string    `json:"type,omitempty"`
	CreatedAt       time.Time `json:"createdAt,omitempty"`
	UpdatedAt       time.Time `json:"updatedAt,omitempty"`
	AccessKeyId     string    `json:"accessKeyId,omitempty"`
	SecretAccessKey string    `json:"secretAccessKey,omitempty"`
}
