/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type Group struct {
	// Name of the group.
	Name string `json:"name"`
	// Indicates that the group is default.
	IsDefault bool `json:"isDefault"`
	// Group applications.
	Applications []string `json:"applications"`
	// Group networks.
	Networks []string `json:"networks"`
	// Group VPN locations.
	VpnLocations []string `json:"vpnLocations"`
	// Group members.
	Users []string `json:"users"`
	// Unique ID.
	Id string `json:"id"`
	// ID of the tenant.
	TenantId string `json:"tenantId"`
	// The date when this record was created.
	CreatedAt string `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt string `json:"updatedAt,omitempty"`
}
