/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type Network struct {
	// DNS of the network.
	Dns string `json:"dns"`
	// Subnet of the network.
	Subnet     string `json:"subnet"`
	AccessType string `json:"accessType"`
	// List of IDs of assigned applications.
	Applications []string `json:"applications"`
	// List of network tags.
	Tags []string `json:"tags"`
	// Network name.
	Name string `json:"name"`
	// Indicates that the network is default.
	IsDefault bool `json:"isDefault"`
	// Network regions list.
	Regions []NetworkRegion `json:"regions"`
	// Unique ID.
	Id string `json:"id"`
	// ID of the tenant.
	TenantId string `json:"tenantId"`
	// The date when this record was created.
	CreatedAt string `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt string `json:"updatedAt,omitempty"`
}
