/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

// IDP connections of the user.
type IdProviderMap struct {
	AdLdap   *IdProvider `json:"adLdap,omitempty"`
	AzureAD  *IdProvider `json:"azureAD,omitempty"`
	Database *IdProvider `json:"database,omitempty"`
	Gsuite   *IdProvider `json:"gsuite,omitempty"`
	Okta     *IdProvider `json:"okta,omitempty"`
	Saml     *IdProvider `json:"saml,omitempty"`
}
