/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type CreateIpSecRedundantPayload struct {
	TunnelName       string                       `json:"tunnelName,omitempty"`
	RegionID         string                       `json:"regionID,omitempty"`
	Tunnel1          *IpSecRedundantTunnelPayload `json:"tunnel1,omitempty"`
	Tunnel2          *IpSecRedundantTunnelPayload `json:"tunnel2,omitempty"`
	SharedSettings   *IpSecSharedSettings         `json:"sharedSettings,omitempty"`
	AdvancedSettings *IpSecAdvancedSettings       `json:"advancedSettings,omitempty"`
}
