/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type CreateGroupPayload struct {
	// The name of the new group.
	Name string `json:"name"`
	// The description of the new group.
	Description string `json:"description,omitempty"`
}
