/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type GroupList struct {
	// List of groups.
	Data []Group `json:"data"`
	// Page number.
	Page float64 `json:"page"`
	// Total pages in list.
	TotalPage float64 `json:"totalPage"`
	// Items in total.
	ItemsTotal float64 `json:"itemsTotal"`
}
