/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type User struct {
	InitialsColor      string `json:"initialsColor"`
	InvitationAttempts int32  `json:"invitationAttempts"`
	// Invitation token.
	InvitationToken string `json:"invitationToken"`
	// Reference ID to `Role`.
	Role        string         `json:"role"`
	IdProviders *IdProviderMap `json:"idProviders"`
	// Invitation message sent to the user.
	InviteMessage string `json:"inviteMessage"`
	// Indicates that the user has been deleted.
	Terminated bool `json:"terminated"`
	// User email.
	Email string `json:"email"`
	// Whether the user verified his email.
	EmailVerified bool `json:"emailVerified"`
	// User initials.
	Initials string `json:"initials"`
	// User role name.
	RoleName string `json:"roleName"`
	// User last name.
	LastName string `json:"lastName"`
	// User first name.
	FirstName string `json:"firstName"`
	// User name.
	Username string `json:"username"`
	// Unique ID.
	Id string `json:"id"`
	// ID of the tenant.
	TenantId string `json:"tenantId"`
	// The date when this record was created.
	CreatedAt string `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt string `json:"updatedAt,omitempty"`
}
