/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type TokenData struct {
	// token type.
	TokenType string `json:"tokenType"`
	// api access token.
	AccessToken string `json:"accessToken"`
	// api access token expire date.
	AccessTokenExpire int64 `json:"accessTokenExpire"`
}

type Token struct {
	TokenData TokenData `json:"data"`
}
